In [1]:
import numpy as np
from numpy import *
np.set_printoptions(threshold=np.inf)
from Queue import Queue
import time

In [19]:
class Node(object):
    def __init__(self,parent=None,val=()):
        self.parent=parent
        self.val=val
    def get_val(self):
        return self.val
    def get_parent(self):
        return self.parent

In [2]:
#Getting Inputs Ready
def get_content(path):
        with  open(path) as f:
            content = f.readlines()

        content= [list(x.strip()) for x in content]
        map_content = np.asanyarray(content)
        return map_content


In [24]:
#finding the path
def get_path(goal,map_content,out):
        
        node=goal.get_parent()
        while(True):
            
            pos=node.get_val()
            if map_content[pos] != 's':
                map_content[pos]='X'
                node=node.get_parent()
                
            else: break
                
            np.savetxt(out+'path.txt', map_content,fmt= '%c',delimiter="")
            f = open(out+'.txt', 'r')
            file_contents = f.read()
            print (file_contents)
            f.close()

In [22]:
#Function for Breadth first search

map1_content=get_content("map1.txt")
map2_content=get_content("map2.txt")
map3_content=get_content("map3.txt")
#print map1_content
#print map1_content.shape

def bfs(map_content,out):
            
            map_queue=Queue()
            start_point=np.where(map_content=='s')
            
            root=Node(None,start_point)
            iteration_count=map_content.shape[0]*map_content.shape[1]
            
            goal_count=0
            goal_position=list()
            
            map_queue.put(root)
            
            

            while (iteration_count>0):

                iteration_count-=1
                
                if map_queue.empty():
                    break
                Possible_direction=[0,0,0,0]
                node=map_queue.get()
                node_pos=node.get_val()
                print node_pos
                print map_content[node_pos]
                
                if map_content[node_pos]!='s':
                    map_content[node_pos]='D'
                    
                if map_content[node_pos[0]-1,node_pos[1]]=='*' or map_content[node_pos[0]-1,node_pos[1]]==' ':

                    if map_content[node_pos[0]-1,node_pos[1]]=='*':
                        goal_position.append((node_pos[0]-1,node_pos[1]))
                        goal_count+=1
                       
                    map_content[node_pos[0]-1,node_pos[1]]='A'
                    child=Node(node,(node_pos[0]-1,node_pos[1]))
                    map_queue.put(child)
                    Possible_direction[0]=1

                if map_content[node_pos[0],node_pos[1]+1]=='*' or map_content[node_pos[0],node_pos[1]+1]==' ':

                    if map_content[node_pos[0],node_pos[1]+1]=='*':
                        goal_position.append((node_pos[0],node_pos[1]+1))
                        goal_count+=1
                        
                    map_content[node_pos[0],node_pos[1]+1]='A'
                    child=Node(node,(node_pos[0],node_pos[1]+1))
                    map_queue.put(child)
                    Possible_direction[1]=1

                if map_content[node_pos[0]+1,node_pos[1]]=='*' or map_content[node_pos[0]+1,node_pos[1]]==' ':

                    if map_content[node_pos[0]+1,node_pos[1]]=='*':
                        goal_position.append((node_pos[0]+1,node_pos[1]))
                        goal_count+=1
                        
                    map_content[node_pos[0]+1,node_pos[1]]='A'
                    child=Node(node,(node_pos[0]+1,node_pos[1]))
                    map_queue.put(child)
                    Possible_direction[2]=1

                if map_content[node_pos[0],node_pos[1]-1]=='*' or map_content[node_pos[0],node_pos[1]-1]==' ':

                    if map_content[node_pos[0],node_pos[1]-1]=='*':
                        goal_position.append((node_pos[0],node_pos[1]-1))
                        goal_count+=1
                        #print ("Goal foundL")
                    map_content[node_pos[0],node_pos[1]-1]='A'
                    child=Node(node,(node_pos[0],node_pos[1]-1))
                    map_queue.put(child)
                    Possible_direction[3]=1
                    
                
                
                if Possible_direction == [1,0,0,0]:
                    map_content[node_pos] = "\u2575"
                elif Possible_direction == [0,1,0,0]:
                    map_content[node_pos] = "\u2577"
                elif Possible_direction == [0,0,1,0]:
                    map_content[node_pos] = "\u2576"
                elif Possible_direction == [0,0,0,1]:
                    map_content[node_pos] = "\u2574"
                elif Possible_direction == [1,1,0,0]:
                    map_content[node_pos] = "\u2502"
                elif Possible_direction == [1,0,1,0]:
                    map_content[node_pos] = "\u2514"
                elif Possible_direction == [1,0,0,1]:
                    map_content[node_pos] = "\u2518"
                elif Possible_direction == [0,1,1,0]:
                    map_content[node_pos] = "\u250C"
                elif Possible_direction == [0,1,0,1]:
                    map_content[node_pos] = "\u2510"
                elif Possible_direction == [0,0,1,1]:
                    map_content[node_pos] = "\u2500"
                elif Possible_direction == [0,1,1,1]:
                    map_content[node_pos] = "\u252C"
                elif Possible_direction == [1,0,1,1]:
                    map_content[node_pos] = "\u2534"
                elif Possible_direction == [1,1,1,1]:
                    map_content[node_pos] = "\u253C"
                elif Possible_direction == [1,1,0,1]:
                    map_content[node_pos] = "\u2524"
                elif Possible_direction == [1,1,1,0]:
                    map_content[node_pos] = "\u251C"
                else:
                    map_content[node_pos] = "\u2576"

                


            for i in goal_position:
                map_content[i]='*'
            
            np.savetxt(out+'.txt', map_content,fmt= '%c',delimiter="")  
            print ("Goals discoverable by BFS for the map is= {}".format(goal_count))
            print ("Goal positions are={}".format(goal_position))
            return (goal_count,goal_position,child)
        
             

#goal_count_1,goal_pos_1=bfs(map1_content,'out1_bfs')       
#goal_count_2,goal_pos_2=bfs(map2_content,'out2_bfs') 
root=Node()
goal_count_3,goal_pos_3,root=bfs(map3_content,'out3_bfs') 

print root.get_parent().get_val()


(array([10]), array([67]))
['s']
(array([9]), array([67]))
['A']
(array([10]), array([68]))
['A']
(array([11]), array([67]))
['A']
(array([10]), array([66]))
['A']
(array([8]), array([67]))
['A']
(array([9]), array([68]))
['A']
(array([9]), array([66]))
['A']
(array([10]), array([69]))
['A']
(array([11]), array([68]))
['A']
(array([12]), array([67]))
['A']
(array([11]), array([66]))
['A']
(array([10]), array([65]))
['A']
(array([7]), array([67]))
['A']
(array([8]), array([68]))
['A']
(array([8]), array([66]))
['A']
(array([9]), array([69]))
['A']
(array([9]), array([65]))
['A']
(array([10]), array([70]))
['A']
(array([11]), array([69]))
['A']
(array([12]), array([68]))
['A']
(array([13]), array([67]))
['A']
(array([12]), array([66]))
['A']
(array([11]), array([65]))
['A']
(array([10]), array([64]))
['A']
(array([6]), array([67]))
['A']
(array([7]), array([68]))
['A']
(array([7]), array([66]))
['A']
(array([8]), array([69]))
['A']
(array([8]), array([65]))
['A']
(array([9]), array([70])

(array([19]), array([73]))
['A']
(array([19]), array([61]))
['A']
(array([18]), array([60]))
['A']
(array([17]), array([59]))
['A']
(array([16]), array([58]))
['A']
(array([15]), array([57]))
['A']
(array([14]), array([56]))
['A']
(array([13]), array([55]))
['A']
(array([12]), array([54]))
['A']
(array([11]), array([53]))
['A']
(array([10]), array([52]))
['A']
(array([1]), array([74]))
['A']
(array([1]), array([60]))
['A']
(array([2]), array([75]))
['A']
(array([2]), array([59]))
['A']
(array([3]), array([76]))
['A']
(array([3]), array([58]))
['A']
(array([4]), array([77]))
['A']
(array([4]), array([57]))
['A']
(array([5]), array([56]))
['A']
(array([6]), array([55]))
['A']
(array([7]), array([54]))
['A']
(array([8]), array([53]))
['A']
(array([9]), array([52]))
['A']
(array([17]), array([76]))
['A']
(array([18]), array([75]))
['A']
(array([19]), array([74]))
['A']
(array([19]), array([60]))
['A']
(array([18]), array([59]))
['A']
(array([17]), array([58]))
['A']
(array([16]), array([57

(array([14]), array([43]))
['A']
(array([13]), array([42]))
['A']
(array([12]), array([41]))
['A']
(array([11]), array([40]))
['A']
(array([10]), array([39]))
['A']
(array([1]), array([87]))
['A']
(array([1]), array([47]))
['A']
(array([2]), array([88]))
['A']
(array([2]), array([46]))
['A']
(array([3]), array([89]))
['A']
(array([3]), array([45]))
['A']
(array([4]), array([90]))
['A']
(array([4]), array([44]))
['A']
(array([5]), array([43]))
['A']
(array([6]), array([42]))
['A']
(array([7]), array([41]))
['A']
(array([8]), array([40]))
['A']
(array([19]), array([47]))
['A']
(array([18]), array([46]))
['A']
(array([17]), array([45]))
['A']
(array([16]), array([44]))
['A']
(array([15]), array([43]))
['A']
(array([14]), array([42]))
['A']
(array([13]), array([41]))
['A']
(array([12]), array([40]))
['A']
(array([11]), array([39]))
['A']
(array([10]), array([38]))
['A']
(array([1]), array([88]))
['A']
(array([1]), array([46]))
['A']
(array([2]), array([89]))
['A']
(array([2]), array([45]))

(array([8]), array([99]))
['A']
(array([9]), array([98]))
['A']
(array([10]), array([97]))
['A']
(array([11]), array([96]))
['A']
(array([12]), array([95]))
['A']
(array([13]), array([94]))
['A']
(array([12]), array([93]))
['A']
(array([11]), array([92]))
['A']
(array([10]), array([91]))
['A']
(array([9]), array([90]))
['A']
(array([8]), array([89]))
['A']
(array([7]), array([88]))
['A']
(array([6]), array([87]))
['A']
(array([4]), array([31]))
['A']
(array([6]), array([31]))
['A']
(array([5]), array([30]))
['A']
(array([19]), array([34]))
['A']
(array([18]), array([33]))
['A']
(array([17]), array([32]))
['A']
(array([1]), array([101]))
['A']
(array([1]), array([33]))
['A']
(array([2]), array([102]))
['A']
(array([3]), array([103]))
['A']
(array([4]), array([104]))
['A']
(array([5]), array([103]))
['A']
(array([6]), array([102]))
['A']
(array([7]), array([101]))
['A']
(array([8]), array([100]))
['A']
(array([9]), array([99]))
['A']
(array([10]), array([98]))
['A']
(array([11]), array([

(array([13]), array([86]))
['A']
(array([12]), array([85]))
['A']
(array([11]), array([84]))
['A']
(array([10]), array([83]))
['A']
(array([9]), array([82]))
['A']
(array([8]), array([81]))
['A']
(array([7]), array([80]))
['A']
(array([6]), array([79]))
['A']
(array([1]), array([26]))
['A']
(array([2]), array([25]))
['A']
(array([3]), array([24]))
['A']
(array([4]), array([23]))
['A']
(array([8]), array([25]))
['A']
(array([7]), array([24]))
['A']
(array([6]), array([23]))
['A']
(array([5]), array([22]))
['A']
(array([19]), array([26]))
['A']
(array([18]), array([25]))
['A']
(array([15]), array([26]))
['A']
(array([16]), array([25]))
['A']
(array([17]), array([24]))
['A']
(array([1]), array([109]))
['A']
(array([2]), array([110]))
['A']
(array([3]), array([111]))
['A']
(array([4]), array([112]))
['A']
(array([6]), array([110]))
['A']
(array([7]), array([109]))
['A']
(array([8]), array([108]))
['A']
(array([9]), array([107]))
['A']
(array([10]), array([106]))
['A']
(array([11]), array([

(array([7]), array([14]))
['A']
(array([6]), array([13]))
['A']
(array([5]), array([12]))
['A']
(array([19]), array([16]))
['A']
(array([18]), array([15]))
['A']
(array([13]), array([18]))
['A']
(array([14]), array([17]))
['A']
(array([15]), array([16]))
['A']
(array([16]), array([15]))
['A']
(array([17]), array([14]))
['A']
(array([1]), array([119]))
['A']
(array([2]), array([120]))
['A']
(array([3]), array([121]))
['A']
(array([4]), array([122]))
['A']
(array([16]), array([110]))
['A']
(array([17]), array([109]))
['A']
(array([18]), array([108]))
['A']
(array([19]), array([107]))
['A']
(array([19]), array([81]))
['A']
(array([18]), array([80]))
['A']
(array([17]), array([79]))
['A']
(array([16]), array([78]))
['A']
(array([1]), array([15]))
['A']
(array([2]), array([14]))
['A']
(array([3]), array([13]))
['A']
(array([4]), array([12]))
['A']
(array([10]), array([20]))
['A']
(array([11]), array([19]))
['A']
(array([12]), array([18]))
['A']
(array([11]), array([17]))
['A']
(array([10]),

(array([3]), array([131]))
['A']
(array([4]), array([132]))
['A']
(array([8]), array([112]))
['A']
(array([9]), array([113]))
['A']
(array([10]), array([114]))
['A']
(array([11]), array([115]))
['A']
(array([12]), array([116]))
['A']
(array([13]), array([117]))
['A']
(array([14]), array([118]))
['A']
(array([15]), array([119]))
['A']
(array([16]), array([120]))
['A']
(array([17]), array([119]))
['A']
(array([18]), array([118]))
['A']
(array([19]), array([117]))
['A']
(array([1]), array([5]))
['A']
(array([2]), array([4]))
['A']
(array([3]), array([3]))
['A']
(array([4]), array([2]))
['A']
(array([12]), array([8]))
['A']
(array([11]), array([7]))
['A']
(array([10]), array([6]))
['A']
(array([9]), array([5]))
['A']
(array([8]), array([4]))
['A']
(array([7]), array([3]))
['A']
(array([6]), array([2]))
['A']
(array([5]), array([1]))
['A']
(array([13]), array([7]))
['A']
(array([14]), array([6]))
['A']
(array([15]), array([5]))
['A']
(array([16]), array([4]))
['A']
(array([1]), array([130])

In [7]:
#Function for Depth first search
map1_content=get_content("map1.txt")
map2_content=get_content("map2.txt")
map3_content=get_content("map3.txt")


def dfs(map_content,out):
            
            map_queue=list()
            start_point=np.where(map_content=='s')
            

            iteration_count=map_content.shape[0]*map_content.shape[1]
            
            goal_count=0
            goal_position=list()
            
            map_queue.append(start_point)
            


            while (iteration_count>0):

                iteration_count-=1
                
                if len(map_queue)==0:
                    break
                
                node=map_queue.pop()
                
                if map_content[node]!='s':
                    map_content[node]='D'
                    
                    
                if map_content[node[0],node[1]-1]=='*' or map_content[node[0],node[1]-1]==' ':

                    if map_content[node[0],node[1]-1]=='*':
                        goal_position.append((node[0],node[1]-1))
                        goal_count+=1
                        
                    map_content[node[0],node[1]-1]='A'
                    map_queue.append((node[0],node[1]-1))
                    

                if map_content[node[0]+1,node[1]]=='*' or map_content[node[0]+1,node[1]]==' ':

                    if map_content[node[0]+1,node[1]]=='*':
                        goal_position.append((node[0]+1,node[1]))
                        goal_count+=1
                        
                    map_content[node[0]+1,node[1]]='A'
                    map_queue.append((node[0]+1,node[1]))
                    
                    
                if map_content[node[0],node[1]+1]=='*' or map_content[node[0],node[1]+1]==' ':

                    if map_content[node[0],node[1]+1]=='*':
                        goal_position.append((node[0],node[1]+1))
                        goal_count+=1
                        
                    map_content[node[0],node[1]+1]='A'
                    map_queue.append((node[0],node[1]+1))
                    
                    
                    
                if map_content[node[0]-1,node[1]]=='*' or map_content[node[0]-1,node[1]]==' ':

                    if map_content[node[0]-1,node[1]]=='*':
                        goal_position.append((node[0]-1,node[1]))
                        goal_count+=1
                       
                    map_content[node[0]-1,node[1]]='A'
                    map_queue.append((node[0]-1,node[1]))
                    
                    
                print map1_content
                time.sleep(0.2)


            for i in goal_position:
                map_content[i]='*'
            np.savetxt(out+'.txt', map_content,fmt= '%c',delimiter="")  
            print ("Goals discoverable by BFS for the map is= {}".format(goal_count))
            print ("Goal positions are={}".format(goal_position))
            return (goal_count,goal_position)
        
             

#goal_count_1,goal_pos_1=dfs(map1_content,'out1_dfs')       
#goal_count_2,goal_pos_2=dfs(map2_content,'out2_dfs') 
#goal_count_3,goal_pos_3=dfs(map3_content,'out3_dfs') 

    

In [5]:
#Function for iterative-deepening depth-first search

In [6]:
#visualize
def visualize_path(map_content, goal_position):
    
    startpoint=np.where(map1_content=='s')
    
    
    